# Generated by Django 4.1.5 on 2023-01-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('place', models.CharField(max_length=155)),
                ('roll_no', models.IntegerField()),
                ('email', models.EmailField(max_length=120)),
            ],
        ),
    ]
