# Generated by Django 4.1.5 on 2023-01-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customer_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='place',
            field=models.CharField(max_length=155),
        ),
    ]
